#!/bin/bash

CXX='g++'
CXXFLAGS='-x c++ -g -O2 -std=gnu++17 -static'

exe() {
  echo "$@"
  "$@"
}

compile() {
  for program in "$@"; do
    exe ${CXX} ${CXXFLAGS} -o ${program}/a.out ${program}/*.cpp
  done
}

if [[ "$#" -eq 0 ]]; then
  for directory in */; do
    compile ${directory%/}
  done
elif [[ "$#" -eq 1 ]] && [[ "$1" == 'clean' ]]; then
  for directory in */; do
    exe rm -f ${directory%/}/a.out
  done
else
  compile "${@:1}"
fi
